source 'https://rubygems.org'

ruby '~> 2.4.4'

gem 'activerecord', '~> 5.0', '>= 5.0.0.1'
gem 'awesome_print'
gem 'dotenv', '~> 2.5'
gem 'down'
gem 'faraday'
gem 'faraday_middleware'
gem 'fileutils'
gem 'forecast_io'
gem 'pg', '>= 0.19.0.beta'
gem 'redd', '~> 0.8.8'
gem 'telegram-bot-ruby', '~> 0.8.6.1'
gem 'timezone', '~> 1.0'
gem 'nokogiri'