source 'https://rubygems.org'

ruby '~> 2.4.4'

gem 'activerecord', '~> 5.0', '>= 5.0.0.1'
gem 'activesupport', '~> 5.2.3'
gem 'awesome_print'
gem 'byebug'
gem 'concurrent-ruby', require: 'concurrent'
gem 'dotenv', '~> 2.5'
gem 'down'
gem 'faraday'
gem 'faraday_middleware'
gem 'fastimage'
gem 'fileutils'
gem 'forecast_io'
gem 'pg', '>= 0.19.0.beta'
gem 'redd', '~> 0.8.8'
gem 'rmagick'
gem 'telegram-bot-ruby', '~> 0.16.0'
gem 'timezone', '~> 1.0'
gem 'nokogiri'
gem 'streamio-ffmpeg'